name: Sync Backend to Hugging Face
on:
  push:
    branches: [updated]
    paths:
      - 'backend-project/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "deploy@github.com"
          git config --global user.name "GitHub Action"
          
          # Gunakan subtree split dan force push
          COMMIT_SHA=$(git subtree split --prefix backend-project HEAD)
          git push https://Feliciaaaaaaaaae:$HF_TOKEN@huggingface.co/spaces/Feliciaaaaaaaaae/backendwinosa $COMMIT_SHA:main --force
